### ISSUE TITLE
effect in nav-bar doesn't work

### ISSUE THREAD

**Issue by linkito87** [ionic-team/ionic-contrib-frosted-glass#8]
Hi.

I'm trying to put the effect in a nav-bar tag, but this doesn't works....

```
<ion-header-bar frosted-bar class="bar-positive" title="'Blurred...man!'" type="bar-frosted">
</ion-header-bar>

<ion-nav-view name="mainContent">
</ion-nav-view>
```

This code works, but this not:

```
<ion-nav-bar frosted-bar class="bar-positive" type="bar-frosted">
    <ion-nav-back-button class="button-clear"><i class="icon ion-ios7-arrow-back"></i> Atrás</ion-nav-back-button>
</ion-nav-bar>

<ion-nav-view name="mainContent">   
</ion-nav-view>
```

Anybody can help me? Thanks

**Comment by ctwhome** [comment]
Hi!

did you find a solution for that?

regards

**Comment by smlu** [comment]
The problem is line 35: 

``` javascript
 var elHeight = el.offsetHeight; 
```

The  `offsetHeight` of nav-bar is 0. To get it working you have to get the offsetHeight of its childNode header-bar. Something like this: `el.querySelector("ion-header-bar").offsetHeight`.
You also have to update the `z-index` of `ionic-contrib-blur` class to 9 in  ionic.contrib.frostedGlass.css.

Note: I've already made pull request on this issue
